default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %> 


test:
  <<: *default
  database: myapp_test
