name: ci
run-name: ${{ github.actor}} is learning GitHub Actions
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: 
      image: ruby:3.0.2
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: apt-get -yqq install libpq-dev

      - name: Run bundle install
        run: |
          bundle config set without development production
          bundle config path vendor/bundle
          bundle config set deployment 'true'
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          bundle exec rails db:prepare db:migrate RAILS_ENV=test

    