name: ci
run-name: ${{ github.actor}} is learning GitHub Actions
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: 
      image: ruby:3.1
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Show Ruby version
        run : |
          ruby -v
      # - name: Install dependencies
      #   run: |
      #     bundle install
      # - name: Run tests
      #   run: |
      #     bundle exec rake test
    